AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 with Nginx using CloudFormation

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the default VPC

Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  SimpleEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-02db68a01488594c5
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: MySimpleInstance
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y nginx
          systemctl start nginx
          systemctl enable nginx

          echo "<h1>Nginx via CloudFormation</h1>" > /usr/share/nginx/html/index.html

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref SimpleEC2Instance
